spring:
  profiles:
    active: production
  application:
    name: datalog-parser

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dataLogging

column-configuration:
  device-time: 1
  intake-air-temperature: 14

---
spring:
  config:
    activate:
      on-profile: cucumber
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cucumberTest

column-configuration:
  device-time: 0
  intake-air-temperature: 1