spring:
  profiles:
    active: production
  application:
    name: datalog-parser

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dataLogging
      auto-index-creation: true

column-configuration:
  device-time: 1
  longitude: 2
  latitude: 3
  altitude: 6
  coolant-temperature: 12
  engine-rpm: 13
  intake-air-temperature: 14
  speed: 15
  throttle-position: 16
  boost-pressure: 17


---
spring:
  config:
    activate:
      on-profile: cucumber
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cucumberTest
      auto-index-creation: true

column-configuration:
  device-time: 0
  longitude: 1
  latitude: 2
  altitude: 3
  coolant-temperature: 4
  engine-rpm: 5
  intake-air-temperature: 6
  speed: 7
  throttle-position: 8
  boost-pressure: 9
