spring:
  profiles:
    active: production
  application:
    name: datalog-parser

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dataLogging
      auto-index-creation: true

column-configuration:
  device-time: 1
  longitude: 2
  latitude: 3
  altitude: 6
  air-fuel-ratio: 12
  coolant-temperature: 13
  engine-rpm: 14
  intake-air-temperature: 15
  speed: 16
  throttle-position: 17
  boost-pressure: 18

user:
  first-name:
  last-name:
  email:

track-info:
  name: GingerMan (long)
  latitude: 42.4086
  longitude: -86.1374

---
spring:
  config:
    activate:
      on-profile: cucumber
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cucumberTest
      auto-index-creation: true

column-configuration:
  device-time: 0
  longitude: 1
  latitude: 2
  altitude: 3
  coolant-temperature: 4
  engine-rpm: 5
  intake-air-temperature: 6
  speed: 7
  throttle-position: 8
  boost-pressure: 9
  air-fuel-ratio: 10

user:
  first-name: test
  last-name: tester
  email: test@test.com

track-info:
  name: Test Track
  latitude: 42.4086
  longitude: -86.1374
