spring:
  profiles:
    active: production
  application:
    name: datalog-parser

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dataLogging

column-configuration:
  device-time: 1
  coolant-temperature: 12
  engine-rpm: 13
  intake-air-temperature: 14
  speed: 15
  throttle-position: 16
  boost-pressure: 17


---
spring:
  config:
    activate:
      on-profile: cucumber
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cucumberTest

column-configuration:
  device-time: 0
  coolant-temperature: 1
  engine-rpm: 2
  intake-air-temperature: 3
  speed: 4
  throttle-position: 4
  boost-pressure: 5
